plugins {
    id 'com.android.application'
}

android {
    namespace 'com.vynox.app'
    compileSdk 34

    defaultConfig {
        applicationId 'com.vynox.app'
        minSdk 23
        targetSdk 34
        versionCode 9
        versionName "0.9"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
